# Generated by Django 4.1 on 2022-12-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physioweb', '0002_ipscmrna'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneMapHuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensembl', models.CharField(max_length=200)),
                ('gene_symbol', models.CharField(max_length=200)),
                ('biotype', models.CharField(max_length=200)),
            ],
        ),
    ]
