# Generated by Django 4.1 on 2022-12-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physioweb', '0003_genemaphuman'),
    ]

    operations = [
        migrations.CreateModel(
            name='EphysTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.CharField(max_length=200)),
            ],
        ),
    ]
